//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5BoostrapDRAdminV4
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Department
    {
        public TBL_Department()
        {
            this.TBL_EmployeeDetails = new HashSet<TBL_EmployeeDetails>();
        }
    
        public int DepatmentID { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual ICollection<TBL_EmployeeDetails> TBL_EmployeeDetails { get; set; }
    }
}
