//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5BoostrapDRAdminV4
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EmployeeDetails
    {
        public TBL_EmployeeDetails()
        {
            this.TBL_EmployeeLogin = new HashSet<TBL_EmployeeLogin>();
        }
    
        //public override int EmpID { get; set; }
    /*    public string FirstName { get; set; }
        public string LastName { get; set; }
        public int GenderID { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Email { get; set; }
        public string ContactNum { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOA { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string BloodGroup { get; set; }
        public string Mode { get; set; }
        public Nullable<int> OfficeLocationID { get; set; }
        public Nullable<int> TeamLeaderID { get; set; }
        public Nullable<int> ShiftPartnerID { get; set; }
    
        public virtual TBL_Department TBL_Department { get; set; }
        public virtual TBL_Gender TBL_Gender { get; set; }
        public virtual TBL_OfficeLocation TBL_OfficeLocation { get; set; }
        public virtual ICollection<TBL_EmployeeLogin> TBL_EmployeeLogin { get; set; }
     * */
    }
}
