//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5BoostrapDRAdminV4
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EmployeeLogin
    {
        public int LoginId { get; set; }
        //public Nullable<int> EmpID { get; set; }
        public string Password { get; set; }
        //public string Type { get; set; }
        public Nullable<System.DateTime> LastLoginOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual TBL_EmployeeDetails TBL_EmployeeDetails { get; set; }
    }
}
